### ISSUE TITLE
Error (use-package): org-query-gtd :init: Wrong type argument: symbolp,

### ISSUE THREAD

**Issue by ghost** [remyhonig/org-query#1]
@remyhonig Thank you for developing this wonderful package. It's great. But I met a little trouble with it.

I add your package to spacemacs, with use-package,got error:

> Error (use-package): org-query-gtd :init: Wrong type argument: symbolp

```
Error (use-package): org-query-gtd :init: Wrong type argument: symbolp, ("r" "Review Agenda" ((agenda "" ((org-agenda-ndays 1))) (\, (rmh/agendablock-inbox)) (\, (rmh/agendablock-loose-tasks)) (\, (rmh/agendablock-tasks-waiting)) (\, (rmh/agendablock-next-in-active)) (\, (rmh/agendablock-active-projects-with-next)) (\, (rmh/agendablock-active-projects-without-next)) (\, (rmh/agendablock-backlog-of-active)) (\, (rmh/agendablock-checklists))) nil)
```
#### System Info
- OS: darwin
- Emacs: 24.5.1

Hope to get help from you.

**Comment by ghost** [comment]
@remyhonig I have known the reason. So I close it. Thank you for writing this package.

**Comment by remyhonig** [comment]
:+1:  thanks for updating

**Comment by FelixHuoEZ** [comment]
I meet the same problem, so how did you solve this?
